name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  image_create:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
    
   
  deploy_to_test:
    needs: image_create
    runs-on: ubuntu-latest
    steps:
     -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
     -
        name: Build and push
        uses: docker/build-push-action@v3
        with: 
           push: true
           tags: omka/shopsrusbackend:latest
